spring:
  application:
    name: springboot-init
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.157.97.252:4406/sapi
    username: root
    password: yang48690322
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: 82.157.97.252
    password: 123321
    database: 0
server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

sapi:
  client:
    access-key: swx
    secret-key: yang4869

#dubbo:
#  application:
#    name: dubbo-springboot-demo-provider
#  protocol:
#    name: dubbo
#    port: -1
#  registry:
#    id: nacos-registry
#    address: nacos://10.15.25.23:8848

dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://10.15.25.23:2181
    # 配置中心连接时间改为10秒
  config-center:
    timeout: 10000
